// vueJS/src/views/home.vue
<template>
  <div class="home-container"
    ><div class="home-navbar1"
      ><app-navbar4 rootClassName="navbar4-root-class-name"></app-navbar4></div
    ><div class="home-hero2"
      ><app-hero3 rootClassName="hero3-root-class-name"></app-hero3></div
    ><div class="home-logos3"><app-logos1></app-logos1></div
    ><div class="home-gallery4"
      ><app-gallery1 rootClassName="gallery1-root-class-name"></app-gallery1></div
    ><div class="home-features5"><app-features17></app-features17></div
    ><div class="home-features6"><app-features18></app-features18></div
    ><div class="home-features7"
      ><app-features171
        rootClassName="features171-root-class-name"
      ></app-features171></div
    ><div class="home-cta8"><app-cta1></app-cta1></div
    ><div class="home-faq9"
      ><app-faq1 rootClassName="faq1-root-class-name"></app-faq1></div
    ><div class="home-contact10"
      ><app-contact4 rootClassName="contact4-root-class-name"></app-contact4></div
    ><div class="home-footer11"
      ><app-footer15 rootClassName="footer15-root-class-name"></app-footer15></div
  ></div>
</template>

<script>
import AppNavbar4 from '../components/navbar4'
import AppHero3 from '../components/hero3'
import AppLogos1 from '../components/logos1'
import AppGallery1 from '../components/gallery1'
import AppFeatures17 from '../components/features17'
import AppFeatures18 from '../components/features18'
import AppFeatures171 from '../components/features171'
import AppCta1 from '../components/cta1'
import AppFaq1 from '../components/faq1'
import AppContact4 from '../components/contact4'
import AppFooter15 from '../components/footer15'

export default {
  name: 'Home',
  props: {},
  components: {
    AppNavbar4,
    AppHero3,
    AppLogos1,
    AppGallery1,
    AppFeatures17,
    AppFeatures18,
    AppFeatures171,
    AppCta1,
    AppFaq1,
    AppContact4,
    AppFooter15,
  },
  metaInfo: {
    title: 'Jolly Hearty Chicken',
    meta: [
      {
        property: 'og:title',
        content: 'Jolly Hearty Chicken',
      },
    ],
  },
}
</script>

<style scoped>
.home-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
}
.home-navbar1 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-hero2 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-logos3 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-gallery4 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-features5 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-features6 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-features7 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-cta8 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-faq9 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-contact10 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-footer11 {
  flex: 0 0 auto;
  width: 100%;
  height: auto;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>

// react/src/views/home.js
import React from 'react'

import { Helmet } from 'react-helmet'

import Navbar4 from '../components/navbar4'
import Hero3 from '../components/hero3'
import Logos1 from '../components/logos1'
import Gallery1 from '../components/gallery1'
import Features17 from '../components/features17'
import Features18 from '../components/features18'
import Features171 from '../components/features171'
import CTA1 from '../components/cta1'
import FAQ1 from '../components/faq1'
import Contact4 from '../components/contact4'
import Footer15 from '../components/footer15'
import './home.css'

const Home = (props) => {
  return (
    <div className="home-container">
      <Helmet>
        <title>Jolly Hearty Chicken</title>
        <meta property="og:title" content="Jolly Hearty Chicken" />
      </Helmet>
      <div className="home-navbar1">
        <Navbar4 rootClassName="navbar4-root-class-name"></Navbar4>
      </div>
      <div className="home-hero2">
        <Hero3 rootClassName="hero3-root-class-name"></Hero3>
      </div>
      <div className="home-logos3">
        <Logos1></Logos1>
      </div>
      <div className="home-gallery4">
        <Gallery1 rootClassName="gallery1-root-class-name"></Gallery1>
      </div>
      <div className="home-features5">
        <Features17></Features17>
      </div>
      <div className="home-features6">
        <Features18></Features18>
      </div>
      <div className="home-features7">
        <Features171 rootClassName="features171-root-class-name"></Features171>
      </div>
      <div className="home-cta8">
        <CTA1></CTA1>
      </div>
      <div className="home-faq9">
        <FAQ1 rootClassName="faq1-root-class-name"></FAQ1>
      </div>
      <div className="home-contact10">
        <Contact4 rootClassName="contact4-root-class-name"></Contact4>
      </div>
      <div className="home-footer11">
        <Footer15 rootClassName="footer15-root-class-name"></Footer15>
      </div>
    </div>
  )
}

export default Home
